services:
  dnmonster:
    image: amouat/dnmonster:1.0
  identidock:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "5001:5000"
    environment:
      ENV: DEV 
    volumes:
      - ./app:/app
    links:
      - dnmonster